# see http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8

# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# see http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

addons:
  # see https://scan.coverity.com/travis_ci
  # see https://docs.travis-ci.com/user/coverity-scan/
  coverity_scan:
    project:
      name: "sebhoss/suppress-warnings"
      description: "Build submitted via Travis CI"
    notification_email: "metio@googlegroups.com"
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master

# see https://docs.travis-ci.com/user/notifications/
notifications:
  # see https://docs.travis-ci.com/user/notifications/#IRC-notification
  irc: "chat.freenode.net#metio.wtf"
  # see https://docs.travis-ci.com/user/notifications/#Email-notifications
  email:
    - "metio@googlegroups.com"

env:
  global:
    # exposes 'COVERITY_SCAN_TOKEN'
    # see https://scan.coverity.com/travis_ci
    # see https://docs.travis-ci.com/user/coverity-scan/
    - secure: "VrNRhmGfHAZw+B1hQFmSd4k93EQNXejx5DNptcpHxHgZUIkD0djuQyyp5A9P7QeYn9MvDrB3VGFw8Z90kTAh8GPwUr3TWT7LLZ9s3sxHPI3VoqdSHl8utOR1wN7UoawcfBAyGtv/SqhE5e3L8Sb+4CHl1cO7YCf8DBFncGSnBNM="
